modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"
issueTrackerURL="https://github.com/Toma1O6/Configuration/issues"

[[mods]]
modId="configuration"
version="${file.jarVersion}"
displayName="Configuration"
updateJSONURL="https://raw.githubusercontent.com/Toma1O6/UpdateSchemas/master/configuration-forge.json"
logoFile="logo.png"
authors="Toma"
description='''
Library mod which adds annotation based configs which can be in various config formats such as json/yaml/etc.
Provides simple way to edit values via GUI or synchronize data from server
'''

[[dependencies.configuration]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.configuration]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"