modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"
issueTrackerURL="https://github.com/Toma1O6/Configuration/issues"

[[mods]]
modId="configuration"
version="${file.jarVersion}"
displayName="Configuration"
updateJSONURL="https://raw.githubusercontent.com/Toma1O6/UpdateSchemas/master/configuration-forge.json"
logoFile="logo.png"
authors="Toma"
description='''
Library mod which add .json based configs and enables config edits via UI ingame
'''

[[dependencies.configuration]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.configuration]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"