modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT License"
issueTrackerURL="https://github.com/Toma1O6/Configuration/issues" #optional

[[mods]]
modId="configuration"
version="${file.jarVersion}"
displayName="Configuration"
updateJSONURL="https://raw.githubusercontent.com/Toma1O6/Configuration/master/versions.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="logo.png"
authors="Toma"
description='''
Library mod which add .json based configs and enables config edits via UI ingame
'''

[[dependencies.configuration]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.configuration]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"